export const VIDEOS_DATA = [
  {
    id: 'mRc6chDkq4Y',
    title: 'Promocional COHACER 1',
    category: 'promocional',
    badge: 'Promocional',
    isShort: false,
  },
  {
    id: 'CCyjSsoPHQY',
    title: 'Promocional COHACER 2',
    category: 'promocional',
    badge: 'Promocional',
    isShort: false,
  },
  {
    id: 'MjoQgonW1aU',
    title: 'Promocional COHACER 3',
    category: 'promocional',
    badge: 'Promocional',
    isShort: true,
  },
  {
    id: '6hybykGYvsA',
    title: 'Promocional COHACER 4',
    category: 'promocional',
    badge: 'Promocional',
    isShort: true,
  },
  {
    id: '1pyhbLC1sYw',
    title: 'Testimonial COHACER 1',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: false,
  },
  {
    id: '0XzYWEJcxfw',
    title: 'Testimonial COHACER 2',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: 'bwru58dzMB8',
    title: 'Testimonial COHACER 3',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: '9oQavi7FixE',
    title: 'Testimonial COHACER 4',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: 'TCiTx02VQCE',
    title: 'Testimonial COHACER 5',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: '_wj1FyMHTQw',
    title: 'Testimonial COHACER 6',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: '3b2NjVp9Hwg',
    title: 'Testimonial COHACER 7',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: '3Eza62IAECQ',
    title: 'Testimonial COHACER 8',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: '279eXDh6eQM',
    title: 'Testimonial COHACER 9',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: 'vOeIPpFLTPA',
    title: 'Testimonial COHACER 10',
    category: 'testimonial',
    badge: 'Testimonial',
    isShort: true,
  },
  {
    id: 'UfxYtF6adnk',
    title: 'Maestría COHACER',
    category: 'maestria',
    badge: 'Maestría',
    isShort: false,
  },
];
